### ISSUE TITLE
將 Character 設定移至外部設定檔

### ISSUE THREAD

**Issue by sk413025** [SBPLab-LDV/llm-quest-copilot#19]
# 將 Character 設定移至外部設定檔

## 目的
將目前寫死在程式碼中的 Character 設定移至外部設定檔，以便：
- 更容易新增和管理多位病患角色
- 提高系統的可配置性
- 方便非技術人員編輯角色設定

## 建議實作方式

1. 在 `config` 目錄下新增 `characters.yaml` 檔案，格式如下：
```yaml
characters:
  - id: "elena"
    name: "Elena"
    persona: "一位剛動完手術的口腔癌患者"
    backstory: "手術動完之後常常講話別人聽不懂，但還是試圖與醫護人員闡述自己的描述"
    goal: "希望能夠與醫護人員溝通，讓他們了解自己的狀況"
  
  - id: "john"
    name: "John"
    # ... 其他病患設定
```

2. 需要修改的檔案：
- `src/core/character.py`: 新增從 YAML 讀取角色設定的功能
- `main.py`: 修改角色初始化方式
- `src/utils/config.py`: 新增讀取 characters.yaml 的功能

3. 建議新增功能：
- 透過命令列參數選擇要載入的角色
- 支援動態重載角色設定
- 基本的角色設定驗證機制

### 修改建議
- 使用 PyYAML 處理設定檔
- 新增 CharacterLoader 類別處理角色載入邏輯
- 考慮加入角色設定的驗證機制

### 預期的使用方式
```python
# 從設定檔載入角色
character = CharacterLoader.load("elena")
manager = DialogueManager(character)
```

## 驗收標準
- [ ] 完成 `characters.yaml` 設定檔格式定義
- [ ] 實作角色載入機制
- [ ] 更新文件說明新的設定方式
- [ ] 確保現有的測試案例仍能正常運作
- [ ] 新增至少一個測試案例驗證角色載入功能

## 相關文件
- 目前的 README.md 已有專案結構說明
- 需要更新 README.md 加入角色設定的說明

/labels: enhancement, configuration
/milestone: v1.1
